# -*- coding: utf-8 -*-
"""python project weather

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TRhugUaJUSHahQ0UB9fckIefs7Vxn-Pd
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

path_gap ='/content/drive/MyDrive/1. Weather Data.csv'



data = pd.read_csv(path_gap)

data

data.head()

data.tail()

data.shape

data.index

# checking for missing value
data.isnull().sum()

# statistical measures about the data
data.describe()

data.dtypes

data.count()

# checking the distribution of target variable
data['Weather'].value_counts()

data.info()

"""*que 1 .find all the unique 'wind speed' values in the data?*"""

data.head(5)

data.nunique()

weather_data['Wind Speed_km/h'].nunique()

data['Wind Speed_km/h'].unique()

"""*que2.find the number of times when the 'weather is exactly clear?*"""

#value _count
data.Weather.value_counts()

#filtering
data[data.Weather == 'Clear']

#groupby()
data.groupby('Weather').get_group('Clear')

"""*que3.find the numbe of times when the eind speed was exactly 4 km/h?*"""

data[data['Wind Speed_km/h'] == 4]

"""*que4.find out all the null values in  the data?*"""

data.isnull().sum()

data.notnull().sum()

"""*que5.rename the column weather of the dataframe to weather condition?*"""

data.rename(columns={'Weather': 'weather'})

"""*que6.what is the mean 'visibility'?*"""

data.Visibility_km.mean()

"""*que7.what is the standerd deviation of 'pressure'in this data ?*"""

data.Press_kPa.std()

"""*que8what is the variance of relative humidity in this data?*"""

data['Rel Hum_%'].var()

"""*que9.find all instance when snow was recorded.*"""

data['Weather'].value_counts()

data[data['Weather']== 'Snow']

"""*que10.find all instances when wind speed is above 24 and visibility is 25?*"""

data[(data['Wind Speed_km/h'] > 24) & (data['Visibility_km']== 25)]

"""*que11.what is the mean value of each column against each weather condition?*"""

data.groupby('Weather').mean()

"""*que12.what is the minimum and maximum valu of each column against each weather condition?*"""

data.groupby('Weather').min()

data.groupby('Weather').max()

"""*que13.show all  the records where weather condition is fog*"""

data[data['Weather']== 'Fog']

"""*que14.find all instances when weather is clear or visibility is above 40*"""

data[(data['Weather']=='Clear') | (data['Visibility_km'] > 40)]

"""*que15.find all instances when

weather is clear and relative humidity is greater than 50


or

visibility is abovve 40*
"""

data[(data['Weather']== 'Clear')  & ( data['Rel Hum_%'] > 50) | (data['Visibility_km'] > 40)]

"""*"""